### ISSUE TITLE
Problem with Icons

### ISSUE THREAD

**Issue by Java-Jonas** [react-native-community/React-Native-Elements#12] opened 2016-09-12 16:15 UTC
Im trying to use the icons. I think i'm doing everything right, but it just won't work. All i get is a little crossed out box. Does anyone know what I'm doing wrong?
Sorry if this isn't the right place to put this btw. I'm new here.

**Comment by dabit3** [comment] 2016-09-12 16:22
Hey. What version of react-native are you using? Also, did you get any errors when installing the library? Finally, did you restart the packager after installing it? Thanks.

**Comment by dabit3** [comment] 2016-09-13 16:08
@Java-Jonas Any luck with this?

**Comment by Java-Jonas** [comment] 2016-09-13 19:22
my dependencies:
  "dependencies": {
    "react": "15.3.1",
    "react-native": "0.33.0",
    "react-native-elements": "^0.4.0",
    "react-native-vector-icons": "^2.1.0"
  }

restarted everything, still not working. no errors. :(

**Comment by mtzaldo** [comment] 2016-09-13 20:52
I have the same issue, running an example on Android, instead of the icon it displays a square with an X ... here are my dependencies:

"dependencies": {
    "isomorphic-fetch": "^2.2.1",
    "react": "15.2.1",
    "react-native": "0.31.0",
    "react-native-elements": "^0.4.2",
    "react-native-vector-icons": "^2.1.0",
    "react-redux": "^4.4.5"
  }

**Comment by dabit3** [comment] 2016-09-13 21:13
Ok, looking into this now. @Java-Jonas Are you also having this issue on Android, or are you using iOS?

**Comment by dabit3** [comment] 2016-09-13 21:20
Any way I can see your component declarations @mtzaldo @Java-Jonas ? Thanks.

**Comment by mtzaldo** [comment] 2016-09-13 21:35
Yes, I just pushed the code:

https://github.com/mtzaldo/react-native-redux-example

**Comment by dabit3** [comment] 2016-09-13 21:38
@mtzaldo is ListItem the component that's giving you an issue with the icon?

**Comment by mtzaldo** [comment] 2016-09-13 21:50
@dabit3  Yes, that is the one that is not displaying the right-chevron.

**Comment by dabit3** [comment] 2016-09-13 21:51
![screen shot 2016-09-13 at 4 48 26 pm](https://cloud.githubusercontent.com/assets/1857282/18492690/4361c8b8-79d2-11e6-81ba-d082744bfcbc.png)

**Comment by dabit3** [comment] 2016-09-13 21:51
Very interesting, I'm getting it working for some reason. Are there any errors in your console?

**Comment by mtzaldo** [comment] 2016-09-13 21:58
@dabit3 No, I think I could be my emulator. For some reason the font is not being displayed correctly. I thing the issue is not with your components.

![screenshot from 2016-09-13 16-56-32](https://cloud.githubusercontent.com/assets/6621474/18492860/2077fb28-79d3-11e6-92b6-50656d8339bd.png)

**Comment by dabit3** [comment] 2016-09-13 22:01
Have you tried using only the react-native-vector icons in your project? It sounds like it could be an issue with that library being installed correctly, as is often the case I think.

**Comment by mtzaldo** [comment] 2016-09-13 22:04
I will review the library. It is the first time I try it, maybe I need to tweak something. Thanks @dabit3

**Comment by dabit3** [comment] 2016-09-13 22:04
@mtzaldo Ok cool, let me know if you have any more questions!

**Comment by mtzaldo** [comment] 2016-09-13 22:09
@dabit3 Yes, I was missing some lines in **android/app/build.gradle**. The icons are now being displayed correctly. Thanks again. Great project btw!

**Comment by dabit3** [comment] 2016-09-13 22:11
Thanks, glad you got it fixed. Quick note, I noticed that the avatar is not rendering as a circle correctly for some reason. I'm taking a look at this now and will be releasing a fix for this along with some other stuff tonight. @mtzaldo

**Closed** 2016-09-13 22:38 UTC

**Comment by Java-Jonas** [comment] 2016-09-15 06:18
@mtzaldo can you explain me what exactly you did to fix this problem? i really need those icons to work! :(

**Comment by mtzaldo** [comment] 2016-09-15 19:53
@Java-Jonas You can go the repo of the icons: https://github.com/oblador/react-native-vector-icons#android here they tell you what to do to copy the fonts in the device.

**Comment by Radu-Filip** [comment] 2017-03-26 11:11
I was having a similar issue, then I realized I didn't reinstall the app after adding react-native-vector-icons. So a simple` react-native run-android` fixed it for me.

**Comment by xstable** [comment] 2017-08-09 15:57
Same for me like for @raduflp... but I've reinstalled the app.
But anyway I do it again, Kill the App-Process at the emulator and restart the app. Now Icons appear.
:confused:

**Comment by lai32290** [comment] 2018-01-15 23:50
I fix this issue like this step:
-  switch `react-native` to `react-native-cli`.
` $ npm uninstall -g react-native`
`$ npm install -g react-native-cli`

- installing `react-native-elements`
`$ npm install -S react-native-elements`
- installing `react-native-vector-icons`
`$ npm install -S react-native-vector-icons`

- link it to project using `react-native link`
‵$ react-native link react-native-vector-icons`

- rebuild project
`$ react-native run-android`

- restarting development server
`$ npm start`

and that's it! I hope to help you

**Comment by lai32290** [comment] 2018-11-27 09:47
@SOftEngrAtta that's cool! I'm happy for this! 😄

**Comment by romandr25** [comment] 2020-05-10 13:58
Please put it in the "getting started" section.

For me helped:

> Android
> Option: With Gradle (recommended)
> This method has the advantage of fonts being copied from this module at build time so that the fonts and JS are always in sync, making upgrades painless.
> 
> Edit android/app/build.gradle ( NOT android/build.gradle ) and add the following:
> 
> apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"
> To customize the files being copied, add the following instead:
> 
> project.ext.vectoricons = [
>     iconFontNames: [ 'MaterialIcons.ttf', 'EvilIcons.ttf' ] // Name of the font files you want to copy
> ]
> 
> apply from: "../../node_modules/react-native-vector-icons/fonts.gradle"

from here https://github.com/oblador/react-native-vector-icons#android
