### ISSUE TITLE
List Element Scroll Bug

### ISSUE THREAD

**Issue by betoharres** [react-native-community/react-native-elements#251] opened 2017-03-28 00:12 UTC
I'm building a app showing the bus schedules for my city(Brazil), and I was playing with this library when I came across this one problem:

![ListViewBug](http://i.imgur.com/HAt7Gla.gif)

If you scroll a little bit and try to search(which updates the list state) before the animation of scrolling ends, the ListItem will be scrolled up a little bit, and it seems that it's always the exact same amount every time.
I was expecting to the animation stop and reset the List position after updating the ListVew rows.

Here's the repo: 
https://github.com/betoharres/bus-poa-offiline

It's open source, you can clone and run `yarn start`  and `react-native run-ios` to take a look.
It's weird that I couldn't find any open/closed issues about this, it seems so obvious bug that I feel that I've done something wrong.

Anyway, great lib, I loved it ❤️

**Comment by binoy14** [comment] 2017-04-02 06:08
@betoharres I tested your repo and not having this issue. Closing this since it is not reproducible. If you are still having this issue feel free to open it again

**Closed by binoy14** 2017-04-02 06:08 UTC
Labels: bug

**Comment by betoharres** [comment] 2017-04-03 13:07
Sorry, I forgot to close this. I pushed a commit fix to the problem where I was wrapping the `ListView` tag from `react-native` with the tag `List` from react-native-elements. That's why it probably you couldn't reproduced, sorry again for late response.

**Comment by binoy14** [comment] 2017-04-03 17:33
@betoharres no worries, looks great by the way!

**Comment by betoharres** [comment] 2017-04-03 17:42
Thanks!!
