### ISSUE TITLE
Height for ImageStyle in Card not work

### ISSUE THREAD

**Issue by qiluo** [react-native-community/react-native-elements#96] opened 2016-11-24 00:58 UTC
Hi, I've create below stub
```
<Card title='Toothbrush'
        image={require('./images/toothbrush.png')}
        imageStyle={{height:100, width:320}}>
....
</Card>
```

The width worked well, but didn't height, what's wrong with me? thanks

**Comment by binoy14** [comment] 2016-12-10 01:25
Works for me, I am using it inside scrollview. Not sure if that has to do anything with that.

**Comment by dabit3** [comment] 2016-12-22 21:17
@qiluo , I'm unable to reproduce. Can you specify what version or RN you are using and what platform this is on (iOS or Android)? thanks!

**Comment by Monte9** [comment] 2017-02-12 21:30
@qiluo any updates on this? If not, then I'll close this issue as it's not reproducible.

**Closed** 2017-02-21 04:10 UTC
Labels: help wanted

**Comment by AbdulRahman-Proxcurity** [comment] 2019-07-16 10:58
How to position image tag inside card tag center
