### ISSUE TITLE
Search bar on android

### ISSUE THREAD

**Issue by elie222** [react-native-community/react-native-elements#50] opened 2016-09-27 12:50 UTC
This is what the search bar looks like on android at the moment:
![screen shot 2016-09-27 at 3 49 12 pm](https://cloud.githubusercontent.com/assets/3090527/18873856/07cb7b02-84ca-11e6-8a89-ba055e67fc35.png)

**Comment by dabit3** [comment] 2016-10-01 17:22
thanks @elie222 this should now be fixed!

**Comment by elie222** [comment] 2016-10-02 00:41
Search bar now crashes the app:
<img width="386" alt="screen shot 2016-10-02 at 3 41 11 am" src="https://cloud.githubusercontent.com/assets/3090527/19017810/241e67e8-8852-11e6-898c-0d27e16bf572.png">

**Comment by lednhatkhanh** [comment] 2016-12-11 01:48
I'm using the latest version and the searchbar's still look the same as @elie222 mentioned... This should be reopen.

**Comment by dabit3** [comment] 2016-12-12 17:20
I'll check this out today, hope to have a fix and a new version out asap.

**Comment by dabit3** [comment] 2016-12-22 20:58
@monte9 This may be a good issue to jump on if you have the time, thanks.

**Comment by Monte9** [comment] 2016-12-23 00:52
@lednhatkhanh unfortunately, I am unable to reproduce this. I am using SearchBar like such and it looks fine to me: 
```javascript
<SearchBar
   placeholder="Search Players..."
/>
```
![screen shot 2016-12-22 at 4 49 16 pm](https://cloud.githubusercontent.com/assets/7840686/21444825/c25e7e6c-c866-11e6-9315-9232b5fbb56b.png)
Can you share the code you are using that's causing this? Afaik, it should be fixed.

**Comment by dabit3** [comment] 2016-12-23 19:54
Ok, closing this, it also worked for me but removed the default underline and improved the border radius on Android. Thanks @Monte9 for checking this out.

**Closed by dabit3** 2016-12-23 19:54 UTC
